FROM golang:1.12 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o auto-lb .

FROM haproxy:2.0-alpine

COPY --from=builder /app/auto-lb /
ENTRYPOINT ["/auto-lb"]
